name: 'Deploy app to Shopify Oxygen'
branding:
  icon: shopping-bag
  colour: green
description: 'Deploy JavaScript applications to Shopify Oxygen directly from GitHub'
inputs:
  shop_id:
    description: The Shop ID
    required: true
  storefront_id:
    description: The Storefront ID
    required: true
  build_command:
    description: The build command to execute, sets OXYGEN_ASSET_BASE_URL during execution
    required: true
  commit_message:
    description: The message of the commit
    default: ${{ github.event.head_commit.message }}
    required: true
  commit_timestamp:
    description: The timestamp of the commit
    default: ${{ github.event.head_commit.timestamp }}
    required: true
  oxygen_deployment_token:
    description: The JWT deployment token
    required: true
  oxygen_dms_address:
    description: The Oxygen DMS address as in hostname-or-IPv4:port
    default: oxygen-dms.shopifysvc.com
  oxygen_worker_dir:
    description: The name of the directory containing the worker file
    default: dist/worker
  oxygen_client_dir:
    description: The name of the directory with compiled client files
    default: dist/client
  path:
    description: The root path of the project to deploy
  workflow_run_id:
    description: The id of the workflow run
    default: ${{ github.run_id }}
    required: true
outputs:
  url:
    description: URL of the deployment
runs:
  using: 'docker'
  image: 'Dockerfile'
