name: 'Deploy app to Shopify Oxygen'
branding:
  icon: shopping-bag
  colour: green
description: 'Deploy JavaScript applications to Shopify Oxygen directly from GitHub'
inputs:
  build_command:
    description: The build command to execute; OXYGEN_ASSET_BASE_URL is available as a reference to Shopify's CDN for this command
    required: true
  commit_message:
    description: The message of the commit
    default: ${{ github.event.head_commit.message }}
    required: true
  commit_timestamp:
    description: The timestamp of the commit
    default: ${{ github.event.head_commit.timestamp }}
    required: true
  oxygen_deployment_token:
    description: The JWT deployment token
    required: true
  oxygen_dms_address:
    description: The Oxygen DMS address as in hostname-or-IPv4:port
    default: oxygen-dms.shopifysvc.com
  oxygen_worker_dir:
    description: The name of the directory containing the worker file
    default: dist/worker
  oxygen_client_dir:
    description: The name of the directory with compiled client files
    default: dist/client
  path:
    description: The root path of the project to deploy
outputs:
  url:
    description: URL of the deployment
    value: ${{ steps.oxygenctl-action.outputs.url  }}
runs:
  using: 'composite'
  steps:
    - run: '${{ github.action_path }}/entrypoint.sh'
      id: 'oxygenctl-action'
      shell: 'bash'
      env:
        INPUT_BUILD_COMMAND: ${{ inputs.build_command }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit_message }}
        INPUT_COMMIT_TIMESTAMP: ${{ inputs.commit_timestamp }}
        INPUT_OXYGEN_DEPLOYMENT_TOKEN: ${{ inputs.oxygen_deployment_token }}
        INPUT_OXYGEN_DMS_ADDRESS: ${{ inputs.oxygen_dms_address }}
        INPUT_OXYGEN_WORKER_DIR: ${{ inputs.oxygen_worker_dir }}
        INPUT_OXYGEN_CLIENT_DIR: ${{ inputs.oxygen_client_dir }}
        INPUT_PATH: ${{ inputs.path }}
