# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: oxygenctl Action CI

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true

      - name: Setup bot Git user
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Create a Hydrogen app
        run: |
          npm --version
          npm create @shopify/hydrogen@latest -- --template hello-world --language ts --path hydrogen-app --install-deps false

      - name: Get yarn cache directory
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        id: "install-dependencies"
        run: |
          cd hydrogen-app
          yarn

      - name: Deploy to Oxygen
        uses: ./
        id: oxygenctl-action
        with:
          commit_message: ${{ github.event.head_commit.message }}
          commit_timestamp: ${{ github.event.head_commit.timestamp }}
          oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN }}
          path: ./hydrogen-app
          build_command: "HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL yarn build"
          oxygen_health_check: true

      - name: Output check
        run: |
          url='${{ steps.oxygenctl-action.outputs.url }}'
          echo $url
          curl $url -sS
