# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: oxygenctl Action CI

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true

      - name: Create a hydrogen app
        run: |
          npm --version
          npm create @shopify/hydrogen -- --template hydrogen hydrogen-app

      - name: Create config file
        run: |
          cd hydrogen-app
          cat > shopify.config.js <<-END
            ${{ secrets.SHOPIFY_CONFIG }}
          END
          cat shopify.config.js

      - name: Get yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies + build
        run: |
          cd hydrogen-app
          yarn
          yarn build

      - name: oxygenctl Deploy
        uses: ./
        id: oxygenctl-action
        with:
          oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN }}
          oxygen_dms_address: ${{ secrets.OXYGEN_DMS_ADDRESS }}
          commit_message: ${{ github.event.head_commit.message }}
          commit_timestamp: ${{ github.event.head_commit.timestamp }}
          path: ./hydrogen-app

      - name: Output check
        run: |
          url='${{ steps.oxygenctl-action.outputs.url }}'
          echo $url
          curl $url -sS
